'use strict';
/* ============ All learning content ============
   kinds: words · sentences · grammar · dialogues
   Mastery (5 correct in a row) is tracked by engine.js per item. */
window.DATA = (function () {
  const A1W = [
    // greetings
    { es: 'hola', en: 'hello', cat: 'greetings' },
    { es: 'adiós', en: 'goodbye', cat: 'greetings' },
    { es: 'gracias', en: 'thank you', cat: 'greetings' },
    { es: 'por favor', en: 'please', cat: 'greetings' },
    { es: 'de nada', en: "you're welcome", cat: 'greetings' },
    { es: 'buenos días', en: 'good morning', cat: 'greetings' },
    { es: 'buenas noches', en: 'good night', cat: 'greetings' },
    { es: '¿cómo estás?', en: 'how are you?', cat: 'greetings' },
    { es: 'muy bien', en: 'very well', cat: 'greetings' },
    { es: 'hasta luego', en: 'see you later', cat: 'greetings' },
    // verbs
    { es: 'ser', en: 'to be (permanent)', cat: 'verbs' },
    { es: 'estar', en: 'to be (temporary)', cat: 'verbs' },
    { es: 'tener', en: 'to have', cat: 'verbs' },
    { es: 'ir', en: 'to go', cat: 'verbs' },
    { es: 'hacer', en: 'to do / to make', cat: 'verbs' },
    { es: 'hablar', en: 'to speak', cat: 'verbs' },
    { es: 'comer', en: 'to eat', cat: 'verbs' },
    { es: 'beber', en: 'to drink', cat: 'verbs' },
    { es: 'vivir', en: 'to live', cat: 'verbs' },
    { es: 'escuchar', en: 'to listen', cat: 'verbs' },
    { es: 'aprender', en: 'to learn', cat: 'verbs' },
    { es: 'ayudar', en: 'to help', cat: 'verbs' },
    { es: 'llegar', en: 'to arrive', cat: 'verbs' },
    { es: 'salir', en: 'to leave', cat: 'verbs' },
    { es: 'entender', en: 'to understand', cat: 'verbs' },
    { es: 'necesitar', en: 'to need', cat: 'verbs' },
    { es: 'poder', en: 'to be able to', cat: 'verbs' },
    { es: 'querer', en: 'to want', cat: 'verbs' },
    { es: 'jugar', en: 'to play', cat: 'verbs' },
    { es: 'dormir', en: 'to sleep', cat: 'verbs' },
    // food
    { es: 'el agua', en: 'water', cat: 'food' },
    { es: 'el pan', en: 'bread', cat: 'food' },
    { es: 'la leche', en: 'milk', cat: 'food' },
    { es: 'la manzana', en: 'apple', cat: 'food' },
    { es: 'la carne', en: 'meat', cat: 'food' },
    { es: 'el pescado', en: 'fish', cat: 'food' },
    { es: 'el café', en: 'coffee', cat: 'food' },
    { es: 'el desayuno', en: 'breakfast', cat: 'food' },
    { es: 'la cena', en: 'dinner', cat: 'food' },
    { es: 'la comida', en: 'lunch / food', cat: 'food' },
    { es: 'el restaurante', en: 'restaurant', cat: 'food' },
    { es: 'el hambre', en: 'hunger', cat: 'food' },
    { es: 'rico', en: 'tasty', cat: 'food' },
    // family
    { es: 'la familia', en: 'family', cat: 'family' },
    { es: 'la madre', en: 'mother', cat: 'family' },
    { es: 'el padre', en: 'father', cat: 'family' },
    { es: 'el hijo', en: 'son', cat: 'family' },
    { es: 'la hija', en: 'daughter', cat: 'family' },
    { es: 'el hermano', en: 'brother', cat: 'family' },
    { es: 'la hermana', en: 'sister', cat: 'family' },
    { es: 'el abuelo', en: 'grandfather', cat: 'family' },
    { es: 'la abuela', en: 'grandmother', cat: 'family' },
    // travel
    { es: 'la calle', en: 'street', cat: 'travel' },
    { es: 'a la izquierda', en: 'on the left', cat: 'travel' },
    { es: 'a la derecha', en: 'on the right', cat: 'travel' },
    { es: 'la estación', en: 'train station', cat: 'travel' },
    { es: 'el billete', en: 'ticket', cat: 'travel' },
    { es: 'el hotel', en: 'hotel', cat: 'travel' },
    { es: 'la habitación', en: 'room', cat: 'travel' },
    { es: 'el baño', en: 'bathroom', cat: 'travel' },
    { es: 'el hospital', en: 'hospital', cat: 'travel' },
    { es: 'el banco', en: 'bank', cat: 'travel' },
    { es: 'la ciudad', en: 'city', cat: 'travel' },
    { es: 'el mapa', en: 'map', cat: 'travel' },
    { es: 'el taxi', en: 'taxi', cat: 'travel' },
    { es: 'la maleta', en: 'suitcase', cat: 'travel' },
    { es: '¿cuánto cuesta?', en: 'how much is it?', cat: 'travel' },
    { es: 'el cambio', en: 'change (money)', cat: 'travel' },
    // numbers & time
    { es: 'uno', en: 'one', cat: 'numbers & time' },
    { es: 'dos', en: 'two', cat: 'numbers & time' },
    { es: 'tres', en: 'three', cat: 'numbers & time' },
    { es: 'diez', en: 'ten', cat: 'numbers & time' },
    { es: 'veinte', en: 'twenty', cat: 'numbers & time' },
    { es: 'cien', en: 'one hundred', cat: 'numbers & time' },
    { es: 'hoy', en: 'today', cat: 'numbers & time' },
    { es: 'mañana', en: 'tomorrow', cat: 'numbers & time' },
    { es: 'anoche', en: 'last night', cat: 'numbers & time' },
    { es: 'siempre', en: 'always', cat: 'numbers & time' },
    { es: 'a veces', en: 'sometimes', cat: 'numbers & time' },
    { es: 'nunca', en: 'never', cat: 'numbers & time' },
    { es: 'mucho', en: 'a lot', cat: 'numbers & time' },
    { es: 'el tiempo', en: 'time / weather', cat: 'numbers & time' },
  ];

  const A1S = [
    { en: 'I am from Spain.', es: 'Soy de España.', ans: ['Soy', 'de', 'España'], distr: ['eres', 'en', 'del'], explain: 'Origin uses <b>ser</b>: <i>soy</i> = "I am" (yo soy).' },
    { en: 'She is at home.', es: 'Ella está en casa.', ans: ['Ella', 'está', 'en', 'casa'], distr: ['es', 'su', 'a'], explain: 'Location uses <b>estar</b>, not ser: <i>está</i> = "is (located)".' },
    { en: 'I have two cats.', es: 'Tengo dos gatos.', ans: ['Tengo', 'dos', 'gatos'], distr: ['hay', 'mi', 'son'], explain: '"I have" = <b>tengo</b> (the verb <i>tener</i>).' },
    { en: 'I want a coffee, please.', es: 'Quiero un café, por favor.', ans: ['Quiero', 'un', 'café', 'por', 'favor'], distr: ['gracias', 'tu', 'una'], explain: '<b>Quiero</b> = "I want". Use <i>un</i> (masculine) / <i>una</i> (feminine) for "a".' },
    { en: 'We are going to the store.', es: 'Vamos a la tienda.', ans: ['Vamos', 'a', 'la', 'tienda'], distr: ['va', 'en', 'del'], explain: '<b>Vamos</b> = "we go" — the verb <i>ir</i> for nosotros (we).' },
    { en: 'I like chocolate.', es: 'Me gusta el chocolate.', ans: ['Me', 'gusta', 'el', 'chocolate'], distr: ['amo', 'a', 'me'], explain: '<b>Gustar</b> runs backwards: literally "chocolate is pleasing to me".' },
    { en: 'Do you speak English?', es: '¿Hablas inglés?', ans: ['¿Hablas', 'inglés?'], distr: ['¿Hablo', 'tu', 'es'], explain: 'Question marks: <b>¿</b> opens, <b>?</b> closes. <i>¿Hablas…?</i> is the "tú" (informal you) form.' },
    { en: 'The food is delicious.', es: 'La comida es deliciosa.', ans: ['La', 'comida', 'es', 'deliciosa'], distr: ['está', 'muy', 'un'], explain: 'Permanent qualities use <b>ser</b>: <i>es</i> deliciosa.' },
    { en: 'Where is the bathroom?', es: '¿Dónde está el baño?', ans: ['¿Dónde', 'está', 'el', 'baño?'], distr: ['¿Qué', 'es', 'en'], explain: '"Where is" = <b>¿Dónde está…?</b> — location, so estar, not ser.' },
    { en: 'I do not understand.', es: 'No entiendo.', ans: ['No', 'entiendo'], distr: ['Sí', 'soy', 'nunca'], explain: 'Negate with <b>no</b> before the verb: <i>No entiendo</i>.' },
    { en: 'I can help you.', es: 'Puedo ayudarte.', ans: ['Puedo', 'ayudarte'], distr: ['ayudo', 'tú', 'no'], explain: '<b>Puedo</b> = "I can" (<i>poder</i>). "To help you" = <i>ayudarte</i>.' },
    { en: 'Let us eat now.', es: 'Comamos ahora.', ans: ['Comamos', 'ahora'], distr: ['Comemos', 'Después', 'ya'], explain: '"Let\'s eat" = <b>comamos</b> (nosotros imperative of comer).' },
    { en: 'I live in Madrid.', es: 'Vivo en Madrid.', ans: ['Vivo', 'en', 'Madrid'], distr: ['Vive', 'es', 'del'], explain: '<b>Vivo</b> = "I live" (<i>vivir</i>). Cities take <i>en</i>.' },
    { en: 'She drinks water.', es: 'Ella bebe agua.', ans: ['Ella', 'bebe', 'agua'], distr: ['El', 'Bebo', 'come'], explain: '<b>Bebe</b> = "she drinks" (<i>beber</i> — the e becomes ie in él/ella forms).' },
    { en: 'I need more time.', es: 'Necesito más tiempo.', ans: ['Necesito', 'más', 'tiempo'], distr: ['Quiero', 'nunca', 'muy'], explain: '<b>Necesito</b> = "I need". <i>más</i> = "more".' },
    { en: 'The children play in the park.', es: 'Los niños juegan en el parque.', ans: ['Los', 'niños', 'juegan', 'en', 'el', 'parque'], distr: ['juega', 'es', 'a'], explain: 'Plural: <b>Los niños juegan</b> — "they" verbs end in -an.' },
    { en: 'I am going to bed.', es: 'Me voy a la cama.', ans: ['Me', 'voy', 'a', 'la', 'cama'], distr: ['soy', 'en', 'está'], explain: '"I\'m off to…" = <b>me voy a</b> + the place.' },
    { en: 'My brother is at school.', es: 'Mi hermano está en la escuela.', ans: ['Mi', 'hermano', 'está', 'en', 'la', 'escuela'], distr: ['es', 'a', 'su'], explain: 'Position → <b>estar</b>: <i>está en la escuela</i>.' },
    { en: 'I am learning Spanish.', es: 'Estoy aprendiendo español.', ans: ['Estoy', 'aprendiendo', 'español'], distr: ['soy', 'aprendo', 'a'], explain: '"I am doing" = <b>estoy</b> + -iendo: <i>estoy aprendiendo</i>.' },
    { en: 'See you tomorrow.', es: 'Nos vemos mañana.', ans: ['Nos', 'vemos', 'mañana'], distr: ['ves', 'hoy', 'adiós'], explain: '"See you" = <b>nos vemos</b> (literally: we see ourselves 👀).' },
  ];

  const A1G = [
    { id: 'g-a1-1', en: 'Where is the station?', correct: '¿Dónde está la estación?', wrongs: ['¿Dónde es la estación?', '¿Dónde está la estaciones?'], explain: 'Location uses <b>estar</b> — and the plural needs <i>están</i>.' },
    { id: 'g-a1-2', en: 'She is Mexican.', correct: 'Ella es mexicana.', wrongs: ['Ella está mexicana.', 'Ella es mexicanas.'], explain: 'Nationality uses <b>ser</b>, and the adjective agrees: <i>mexicana</i>.' },
    { id: 'g-a1-3', en: 'I am sleepy.', correct: 'Tengo sueño.', wrongs: ['Eres sueño.', 'Estoy sueño.'], explain: '"To be sleepy" = <b>tener sueño</b> — Spanish uses tener for body states.' },
    { id: 'g-a1-4', en: 'I like coffee.', correct: 'Me gusta el café.', wrongs: ['Yo gosto el café.', 'Me gustan el café.'], explain: '<b>Gustar</b>: "it pleases me". One singular thing → <i>gusta</i>.' },
    { id: 'g-a1-5', en: 'The children are in the park.', correct: 'Los niños están en el parque.', wrongs: ['Los niños son en el parque.', 'Los niño está en el parque.'], explain: 'Position → <b>estar</b>; plural subject → <i>están</i>.' },
    { id: 'g-a1-6', en: 'I understand nothing.', correct: 'No entiendo nada.', wrongs: ['No entiendo algo.', 'No me entiendo nada.'], explain: 'Negation: <b>no</b> + verb. "Nothing" = <i>nada</i> (not <i>algo</i>).' },
    { id: 'g-a1-7', en: 'Can I pay by card?', correct: '¿Puedo pagar con tarjeta?', wrongs: ['¿Puedo pago con tarjeta?', '¿Puedo pagando con tarjeta?'], explain: '<b>Poder + infinitive</b>: puedo pagar (never "puedo pago").' },
    { id: 'g-a1-8', en: 'We are going to the beach.', correct: 'Vamos a la playa.', wrongs: ['Voy a la playa.', 'Van a la playa.'], explain: '"We go" = <b>vamos</b> (ir, nosotros). <i>Voy</i> = I go, <i>van</i> = they go.' },
    { id: 'g-a1-9', en: 'The food is very tasty.', correct: 'La comida está muy rica.', wrongs: ['El comida está muy rica.', 'La comida están muy rica.'], explain: '<i>Comida</i> is feminine → <b>la comida</b>; singular → <i>está</i>.' },
    { id: 'g-a1-10', en: 'How much is the ticket?', correct: '¿Cuánto cuesta el billete?', wrongs: ['¿Cuánto cuesta la billete?', '¿Cuánto cuestan el billete?'], explain: '<i>Billete</i> is masculine → <b>el billete</b>; one thing → <i>cuesta</i>.' },
  ];

  const A2W = [
    { es: 'el dinero', en: 'money', cat: 'money' },
    { es: 'el trabajo', en: 'job', cat: 'work' },
    { es: 'la opinión', en: 'opinion', cat: 'work' },
    { es: 'el problema', en: 'problem', cat: 'work' },
    { es: 'la salud', en: 'health', cat: 'health' },
    { es: 'el médico', en: 'doctor', cat: 'health' },
    { es: 'la farmacia', en: 'pharmacy', cat: 'health' },
    { es: 'la receta', en: 'prescription', cat: 'health' },
    { es: 'el futuro', en: 'future', cat: 'time' },
    { es: 'el plan', en: 'plan', cat: 'planning' },
    { es: 'la idea', en: 'idea', cat: 'planning' },
    { es: 'la solución', en: 'solution', cat: 'planning' },
    { es: 'empezar', en: 'to start', cat: 'verbs' },
    { es: 'terminar', en: 'to finish', cat: 'verbs' },
    { es: 'cambiar', en: 'to change', cat: 'verbs' },
    { es: 'decidir', en: 'to decide', cat: 'verbs' },
    { es: 'visitar', en: 'to visit', cat: 'verbs' },
    { es: 'reservar', en: 'to reserve / book', cat: 'travel' },
    { es: 'pagar', en: 'to pay', cat: 'money' },
    { es: 'viajar', en: 'to travel', cat: 'travel' },
    { es: 'la playa', en: 'beach', cat: 'travel' },
    { es: 'el vuelo', en: 'flight', cat: 'travel' },
    { es: 'el equipaje', en: 'luggage', cat: 'travel' },
    { es: 'la frontera', en: 'border', cat: 'travel' },
    { es: 'la visa', en: 'visa', cat: 'travel' },
    { es: 'el permiso', en: 'permit', cat: 'travel' },
    { es: 'la experiencia', en: 'experience', cat: 'work' },
    { es: 'el accidente', en: 'accident', cat: 'emergencies' },
    { es: 'la emergencia', en: 'emergency', cat: 'emergencies' },
    { es: 'perder', en: 'to lose', cat: 'verbs' },
    { es: 'encontrar', en: 'to find', cat: 'verbs' },
    { es: 'la propina', en: 'tip', cat: 'money' },
    { es: 'el descuento', en: 'discount', cat: 'money' },
    { es: 'la queja', en: 'complaint', cat: 'money' },
    { es: 'el vecino', en: 'neighbor', cat: 'people' },
    { es: 'la costumbre', en: 'custom / habit', cat: 'culture' },
    { es: 'la cuenta', en: 'bill', cat: 'money' },
    { es: 'el pasaporte', en: 'passport', cat: 'travel' },
    { es: 'la aduana', en: 'customs', cat: 'travel' },
    { es: 'el seguro', en: 'insurance', cat: 'money' },
    { es: 'la fiebre', en: 'fever', cat: 'health' },
    { es: 'el dolor', en: 'pain', cat: 'health' },
    { es: 'la tos', en: 'cough', cat: 'health' },
    { es: 'el resfriado', en: 'cold', cat: 'health' },
    { es: 'la alergia', en: 'allergy', cat: 'health' },
    { es: 'el medicamento', en: 'medicine', cat: 'health' },
    { es: 'la cita', en: 'appointment', cat: 'health' },
    { es: 'el itinerario', en: 'itinerary', cat: 'travel' },
    { es: 'la escala', en: 'layover', cat: 'travel' },
    { es: 'el malestar', en: 'malaise', cat: 'health' },
    { es: 'la disculpa', en: 'apology', cat: 'people' },
    { es: 'el consejo', en: 'advice', cat: 'work' },
    { es: 'la sugerencia', en: 'suggestion', cat: 'work' },
    { es: 'el hábito', en: 'habit', cat: 'culture' },
    { es: 'la rutina', en: 'routine', cat: 'culture' },
    { es: 'el estrés', en: 'stress', cat: 'work' },
  ];

  const A2S = [
    { en: 'I was going to call you.', es: 'Iba a llamarte.', ans: ['Iba', 'a', 'llamarte'], distr: ['voy', 'fui', 'llamar'], explain: '<b>Iba a + infinitive</b> = "was about to / intended to" (imperfect of ir).' },
    { en: 'Yesterday I ate a lot.', es: 'Ayer comí mucho.', ans: ['Ayer', 'comí', 'mucho'], distr: ['Hoy', 'como', 'siempre'], explain: 'Preterite of <i>comer</i>: <b>comí</i> (I ate) — a finished action in the past.' },
    { en: 'If I had time, I would travel.', es: 'Si tuviera tiempo, viajaría.', ans: ['Si', 'tuviera', 'tiempo', 'viajaría'], distr: ['tengo', 'viajo', 'el'], explain: 'Hypothetical: <b>si tuviera</b> (subjunctive) + <b>viajaría</b> (conditional).' },
    { en: 'I have been studying Spanish for two years.', es: 'Llevo dos años estudiando español.', ans: ['Llevo', 'dos', 'años', 'estudiando', 'español'], distr: ['desde', 'tengo', 'estudio'], explain: '"I\'ve been… for X time" = <b>llevo</b> + time + -ing.' },
    { en: 'It looks like it is going to rain.', es: 'Parece que va a llover.', ans: ['Parece', 'que', 'va', 'a', 'llover'], distr: ['llueve', 'es', 'va'], explain: '<b>Va a + infinitive</b> = "going to". <i>Parece que…</i> = "it seems that…"' },
    { en: 'I am used to waking up early.', es: 'Estoy acostumbrado a levantarme temprano.', ans: ['Estoy', 'acostumbrado', 'a', 'levantarme', 'temprano'], distr: ['soy', 'me', 'es'], explain: '"Used to" = <b>estoy acostumbrado a</b> + infinitive (reflexive <i>levantarme</i>).' },
    { en: 'Could I have the bill, please?', es: '¿Me trae la cuenta, por favor?', ans: ['¿Me', 'trae', 'la', 'cuenta,', 'por', 'favor?'], distr: ['¿Qué', 'es', 'la'], explain: 'Polite request: <b>¿Me trae…?</b> — "the bill" = <i>la cuenta</i>.' },
    { en: 'I prefer to walk.', es: 'Prefiero caminar.', ans: ['Prefiero', 'caminar'], distr: ['paseo', 'puedo', 'a'], explain: '<b>preferir + infinitive</b>: <i>prefiero caminar</i>.' },
    { en: 'We are waiting for the train.', es: 'Estamos esperando el tren.', ans: ['Estamos', 'esperando', 'el', 'tren'], distr: ['esperamos', 'es', 'el'], explain: '"We\'re waiting" = <b>estamos esperando</b> (estar + -iendo).' },
    { en: 'There is a pharmacy around the corner.', es: 'Hay una farmacia a la esquina.', ans: ['Hay', 'una', 'farmacia', 'a', 'la', 'esquina'], distr: ['está', 'el', 'hay'], explain: '"There is / there are" = <b>hay</b> (it never changes: <i>hay farmacias</i>).' },
    { en: 'I do not think it is worth it.', es: 'No creo que valga la pena.', ans: ['No', 'creo', 'que', 'valga', 'la', 'pena'], distr: ['vale', 'creo', 'es'], explain: 'Negated <b>creer + que</b> → subjunctive: <i>no creo que valga</i>.' },
    { en: 'I will be back in one hour.', es: 'Volveré en una hora.', ans: ['Volveré', 'en', 'una', 'hora'], distr: ['vuelvo', 'estoy', 'una'], explain: 'Future tense: <b>volveré</b> = "I will return".' },
  ];

  const A2G = [
    { id: 'g-a2-1', en: 'Yesterday I ate a paella.', correct: 'Ayer comí una paella.', wrongs: ['Ayer como una paella.', 'Ayer comía una paella.'], explain: 'One finished action yesterday → <b>preterite</b>: comí.' },
    { id: 'g-a2-2', en: 'If I had time, I would travel more.', correct: 'Si tuviera tiempo, viajaría más.', wrongs: ['Si tengo tiempo, viajaría más.', 'Si tuviera tiempo, viajo más.'], explain: 'Hypothetical: <b>si + subjunctive</b> (tuviera) + conditional (viajaría).' },
    { id: 'g-a2-3', en: "I was going to call you, but I couldn't.", correct: 'Iba a llamarte, pero no pude.', wrongs: ['Voy a llamarte, pero no pude.', 'Ibo a llamarte, pero no pude.'], explain: 'Past intention: <b>iba a + infinitive</b>; "I couldn\'t" = no pude.' },
    { id: 'g-a2-4', en: 'Could I have the bill, please?', correct: '¿Me trae la cuenta, por favor?', wrongs: ['¿Me trae la cuentas?', '¿Me traer la cuenta?'], explain: 'Singular <b>la cuenta</b>; polite tú-request: <i>¿Me trae…?</i>' },
    { id: 'g-a2-5', en: 'We are waiting for the train.', correct: 'Estamos esperando el tren.', wrongs: ['Esperamos esperando el tren.', 'Estamos esperamos el tren.'], explain: '"We\'re waiting" = <b>estamos + -iendo</b> (progressive).' },
    { id: 'g-a2-6', en: 'There is a pharmacy around the corner.', correct: 'Hay una farmacia a la esquina.', wrongs: ['Hay un farmacia a la esquina.', 'Ha una farmacia a la esquina.'], explain: '<i>Farmacia</i> is feminine → <b>una</b>; "there is" = <i>hay</i> (never <i>ha</i>).' },
    { id: 'g-a2-7', en: 'I prefer to walk.', correct: 'Prefiero caminar.', wrongs: ['Prefiero a caminar.', 'Prefiero caminando.'], explain: '<b>Preferir + infinitive</b> — no preposition "a".' },
    { id: 'g-a2-8', en: "I don't think it's worth it.", correct: 'No creo que valga la pena.', wrongs: ['No creo que vale la pena.', 'No creo valga la pena.'], explain: 'Negated creer + que → <b>subjunctive</b>: valga. Keep the que.' },
    { id: 'g-a2-9', en: 'I will be back in one hour.', correct: 'Volveré en una hora.', wrongs: ['Volveré una hora.', 'Vuelvo en una hora.'], explain: 'Future: <b>volveré</b>. <i>Vuelvo</i> is present ("I return").' },
    { id: 'g-a2-10', en: "I've been studying for two years.", correct: 'Llevo dos años estudiando.', wrongs: ['Llevo dos años estudio.', 'Desde dos años estudio.'], explain: 'Duration up to now: <b>llevo + time + -ing</b>.' },
  ];

  const B1W = [
    { es: 'por supuesto', en: 'of course', cat: 'conversation' },
    { es: 'o sea', en: 'I mean', cat: 'conversation' },
    { es: 'es decir', en: 'that is to say', cat: 'conversation' },
    { es: 'más o menos', en: 'more or less', cat: 'conversation' },
    { es: 'la verdad', en: 'the truth', cat: 'conversation' },
    { es: 'bueno', en: 'okay, all right', cat: 'conversation' },
    { es: 'en serio', en: 'seriously', cat: 'conversation' },
    { es: 'claro', en: 'of course, sure', cat: 'conversation' },
    { es: 'a lo mejor', en: 'maybe', cat: 'conversation' },
    { es: 'de acuerdo', en: 'agreed', cat: 'conversation' },
    { es: 'discutir', en: 'to argue / discuss', cat: 'verbs' },
    { es: 'sugerir', en: 'to suggest', cat: 'verbs' },
    { es: 'recomendar', en: 'to recommend', cat: 'verbs' },
    { es: 'evitar', en: 'to avoid', cat: 'verbs' },
    { es: 'lograr', en: 'to achieve', cat: 'verbs' },
    { es: 'intentar', en: 'to try', cat: 'verbs' },
    { es: 'conseguir', en: 'to get / manage', cat: 'verbs' },
    { es: 'disculparse', en: 'to apologize', cat: 'verbs' },
    { es: 'agradecer', en: 'to thank', cat: 'verbs' },
    { es: 'reconocer', en: 'to admit / recognize', cat: 'verbs' },
    { es: 'la propuesta', en: 'proposal', cat: 'work' },
    { es: 'la reunión', en: 'meeting', cat: 'work' },
    { es: 'el contrato', en: 'contract', cat: 'work' },
    { es: 'el sueldo', en: 'salary', cat: 'work' },
    { es: 'la vacante', en: 'job opening', cat: 'work' },
    { es: 'el plazo', en: 'deadline', cat: 'work' },
    { es: 'el mareo', en: 'dizziness', cat: 'health' },
    { es: 'la náusea', en: 'nausea', cat: 'health' },
    { es: 'la inflamación', en: 'inflammation', cat: 'health' },
    { es: 'la tensión', en: 'tension / blood pressure', cat: 'health' },
    // idioms (B1 — natives live here)
    { es: 'echar de menos', en: 'to miss (a person or place)', cat: 'idioms' },
    { es: 'ser pan comido', en: 'a piece of cake', cat: 'idioms' },
    { es: 'estar hasta el cuello', en: 'to be up to one\'s neck (in work)', cat: 'idioms' },
    { es: 'no tener pelos en la lengua', en: 'not to mince words', cat: 'idioms' },
    { es: 'quedarse con la boca abierta', en: 'to be left with your mouth open (in shock)', cat: 'idioms' },
    { es: 'ponerse las pilas', en: 'to get your act together', cat: 'idioms' },
    { es: 'estar en las nubes', en: 'to be in the clouds (spaced out)', cat: 'idioms' },
    { es: 'dar en el clavo', en: 'to hit the nail on the head', cat: 'idioms' },
    { es: 'costar un ojo de la cara', en: 'to cost an arm and a leg', cat: 'idioms' },
    { es: 'estar hecho un flan', en: 'to be scared to death', cat: 'idioms' },
    { es: 'tener la sartén por el mango', en: 'to have the upper hand', cat: 'idioms' },
    { es: 'pasar página', en: 'to turn the page / move on', cat: 'idioms' },
    // formal / functional
    { es: 'por lo tanto', en: 'therefore', cat: 'formal' },
    { es: 'en cuanto a', en: 'as for', cat: 'formal' },
    { es: 'desde mi punto de vista', en: 'from my point of view', cat: 'formal' },
    { es: 'a fin de cuentas', en: 'after all', cat: 'formal' },
    { es: 'sin duda', en: 'without a doubt', cat: 'formal' },
    { es: 'de hecho', en: 'in fact', cat: 'formal' },
    { es: 'para empezar', en: 'to begin with', cat: 'formal' },
    { es: 'en principio', en: 'in principle', cat: 'formal' },
    // work
    { es: 'el informe', en: 'report', cat: 'work' },
    { es: 'el colega', en: 'colleague', cat: 'work' },
    { es: 'la jornada', en: 'working day', cat: 'work' },
    { es: 'el permiso', en: 'time off / permit', cat: 'work' },
    { es: 'el turno', en: 'shift / turn', cat: 'work' },
    { es: 'adelantar', en: 'to advance / to pay in advance', cat: 'work' },
    { es: 'negociar', en: 'to negotiate', cat: 'work' },
    { es: 'el acuerdo', en: 'agreement / deal', cat: 'work' },
    // errands & bureaucracy
    { es: 'el trámite', en: 'paperwork / procedure', cat: 'errands' },
    { es: 'la cita', en: 'appointment', cat: 'errands' },
    { es: 'los antecedentes', en: 'background / record (official)', cat: 'errands' },
    { es: 'el recibo', en: 'receipt', cat: 'errands' },
    { es: 'la fianza', en: 'deposit (rental)', cat: 'errands' },
    { es: 'renovar', en: 'to renew', cat: 'errands' },
    { es: 'la garantía', en: 'guarantee / warranty', cat: 'errands' },
    // opinions & feelings
    { es: 'preocupado', en: 'worried', cat: 'emotions' },
    { es: 'orgulloso', en: 'proud', cat: 'emotions' },
    { es: 'decepcionado', en: 'disappointed', cat: 'emotions' },
    { es: 'impresionado', en: 'impressed', cat: 'emotions' },
    { es: 'en desacuerdo', en: 'in disagreement', cat: 'emotions' },
    { es: 'opinar', en: 'to have an opinion', cat: 'emotions' },
  ];

  const B1S = [
    { en: 'I want you to come with me.', es: 'Quiero que vengas conmigo.', ans: ['Quiero', 'que', 'vengas', 'conmigo'], distr: ['vengo', 'vienes', 'viene'], explain: 'Querer + que → <b>subjunctive</b>: vengas (not vienes).' },
    { en: 'It is better if you call first.', es: 'Es mejor que llames primero.', ans: ['Es', 'mejor', 'que', 'llames', 'primero'], distr: ['llamo', 'llamas', 'es'], explain: 'Es mejor + que → <b>subjunctive</b>: llames.' },
    { en: 'I was going to tell you, but I forgot.', es: 'Iba a contártelo pero se me olvidó.', ans: ['Iba', 'a', 'contártelo', 'pero', 'se', 'me', 'olvidó'], distr: ['olvido', 'olvidé', 'voy'], explain: '"I forgot" (involuntary) = <b>se me olvidó</b>.' },
    { en: 'We should meet this weekend.', es: 'Deberíamos encontrarnos este fin de semana.', ans: ['Deberíamos', 'encontrarnos', 'este', 'fin', 'de', 'semana'], distr: ['encontramos', 'debe', 'el'], explain: '"We should" = <b>deberíamos</b> (deber, plural -íamos).' },
    { en: "I haven't been to Mexico City for a long time.", es: 'No he estado en la Ciudad de México en mucho tiempo.', ans: ['No', 'he', 'estado', 'en', 'la', 'Ciudad', 'de', 'México', 'en', 'mucho', 'tiempo'], distr: ['estuve', 'estoy', 'ha'], explain: 'Present perfect: <b>no he estado</b> — recent past connected to now.' },
    { en: "If it rains, we'll stay home.", es: 'Si llueve, nos quedaremos en casa.', ans: ['Si', 'llueve', 'nos', 'quedaremos', 'en', 'casa'], distr: ['queda', 'lluvia', 'quedamos'], explain: 'Real condition: <b>si + present</b>, main clause in <b>future</b>.' },
    { en: 'I hope you can pass the exam.', es: 'Espero que puedas aprobar el examen.', ans: ['Espero', 'que', 'puedas', 'aprobar', 'el', 'examen'], distr: ['puedes', 'aprobó', 'oye'], explain: 'esperar + que → <b>subjunctive</b>: puedas.' },
    { en: 'He is the most helpful person I have met.', es: 'Es la persona más servicial que he conocido.', ans: ['Es', 'la', 'persona', 'más', 'servicial', 'que', 'he', 'conocido'], distr: ['conozco', 'fue', 'muy'], explain: 'superlative + <b>present perfect</b> (he conocido).' },
    { en: 'I don\'t have the document they asked for.', es: 'No tengo el documento que me pidieron.', ans: ['No', 'tengo', 'el', 'documento', 'que', 'me', 'pidieron'], distr: ['pidió', 'tienes', 'ayer'], explain: 'relative <b>que</b> — no extra "lo" (English traps you: "it that" ✗).' },
    { en: 'The appointment was canceled by the office.', es: 'La cita fue cancelada por la oficina.', ans: ['La', 'cita', 'fue', 'cancelada', 'por', 'la', 'oficina'], distr: ['cancelo', 'es', 'cancela'], explain: 'passive: <b>fue + past participle</b>.' },
    { en: 'If I had more time, I would study every day.', es: 'Si tuviera más tiempo, estudiaría todos los días.', ans: ['Si', 'tuviera', 'más', 'tiempo', 'estudiaría', 'todos', 'los', 'días'], distr: ['tengo', 'estudio', 'tendría'], explain: 'unreal condition: <b>imperfect + conditional</b> — never "si tendría".' },
    { en: 'Even if you are tired, keep practicing.', es: 'Aunque estés cansado, sigue practicando.', ans: ['Aunque', 'estés', 'cansado', 'sigue', 'practicando'], distr: ['estás', 'practico', 'pero'], explain: 'aunque + unknown/possible → <b>subjunctive</b>: estés.' },
    { en: 'I think the exam is not going to be that hard.', es: 'Creo que el examen no va a ser tan difícil.', ans: ['Creo', 'que', 'el', 'examen', 'no', 'va', 'a', 'ser', 'tan', 'difícil'], distr: ['creía', 'será', 'mucho'], explain: 'creer + que → <b>indicative</b> (you affirm it).' },
    { en: 'I was so nervous that I could not sleep.', es: 'Estaba tan nervioso que no podía dormir.', ans: ['Estaba', 'tan', 'nervioso', 'que', 'no', 'podía', 'dormir'], distr: ['estoy', 'dormí', 'muy'], explain: '<b>tan … que</b> = so … that.' },
    { en: 'This is the apartment I have been looking for.', es: 'Este es el apartamento que llevo buscando.', ans: ['Este', 'es', 'el', 'apartamento', 'que', 'llevo', 'buscando'], distr: ['busco', 'fui', 'voy'], explain: '<b>llevar + gerund</b> = "I have been …-ing".' },
    { en: 'They are going to pay us on Friday.', es: 'Nos van a pagar el viernes.', ans: ['Nos', 'van', 'a', 'pagar', 'el', 'viernes'], distr: ['pagan', 'pagarán', 'sábado'], explain: '<b>ir a + infinitive</b> = going to.' },
  ];

  const B1G = [
    { id: 'g-b1-1', en: 'I want you to come on Saturday.', correct: 'Quiero que vengas el sábado.', wrongs: ['Quiero que vienes el sábado.', 'Quiero que vengo el sábado.'], explain: 'Querer + que → <b>subjunctive</b> for the other person: vengas.' },
    { id: 'g-b1-2', en: "It's better if you rest.", correct: 'Es mejor que descanses.', wrongs: ['Es mejor que descansas.', 'Es mejor que descanso.'], explain: 'Es mejor + que → <b>subjunctive</b>: descanses.' },
    { id: 'g-b1-3', en: "I've been living here for two years.", correct: 'Llevo dos años viviendo aquí.', wrongs: ['Desde dos años vivo aquí.', 'Llevo dos años vivo aquí.'], explain: 'Duration: <b>llevo + time + -ing</b>. <i>Desde</i> marks a starting point (desde 2020).' },
    { id: 'g-b1-4', en: 'I forgot to call her.', correct: 'Se me olvidó llamarla.', wrongs: ['Me se olvidó llamarla.', 'Olvidése llamarla.'], explain: 'Reflexive order: <b>se me</b> olvidó. "To call her" = llamarla.' },
    { id: 'g-b1-5', en: 'She likes the museums.', correct: 'A ella le gustan los museos.', wrongs: ['A ella le gusta los museos.', 'A ella le gustan la museos.'], explain: 'Plural thing → <b>gustan</b> + <i>los</i> (agreement all the way).' },
    { id: 'g-b1-6', en: "I don't agree with the proposal.", correct: 'No estoy de acuerdo con la propuesta.', wrongs: ['No estoy de acuerdo a la propuesta.', 'No estoy en acuerdo con la propuesta.'], explain: 'Fixed expression: <b>estar de acuerdo con</b>.' },
    { id: 'g-b1-7', en: 'I am glad that you passed the exam.', correct: 'Me alegra que apruebes el examen.', wrongs: ['Me alegra que apruebas el examen.', 'Me alegra que aprobó el examen.'], explain: 'Feelings + que → <b>subjunctive</b>: apruebes (me alegra, me da miedo, me sorprende…).' },
    { id: 'g-b1-8', en: 'He is the lawyer who defended me.', correct: 'Es el abogado que me defendió.', wrongs: ['Es el abogado el cual lo defendió.', 'Es el abogado que lo defendí.'], explain: 'Relative <b>que</b>, no extra "lo" — English "the one that it" has no Spanish twin.' },
    { id: 'g-b1-9', en: 'The invoice is paid on the fifteenth.', correct: 'La factura se paga el día quince.', wrongs: ['La factura se es pagada el día quince.', 'La factura es pagada por uno el día quince.'], explain: 'Spanish passive is <b>se + verb</b> — "is paid by one" is a literal English translation.' },
    { id: 'g-b1-10', en: 'If I had more money, I would pay the debt.', correct: 'Si tuviera más dinero, pagaría la deuda.', wrongs: ['Si tengo más dinero, pagaría la deuda.', 'Si tendría más dinero, pago la deuda.'], explain: 'Unreal condition: <b>si + imperfect + conditional</b> — never "si tendría".' },
  ];

  /* ---------- real conversations ---------- */
  const A1D = [
    {
      id: 'taxi', icon: '🚕', title: 'Taxi al aeropuerto', intro: 'Downtown, 6 a.m. You hail a taxi.',
      lines: [
        { who: 'you', es: 'Perdone, ¿me lleva al aeropuerto?', en: 'Excuse me, can you take me to the airport?', kw: ['aeropuerto', 'lleva'] },
        { who: 'them', es: 'Sí, claro. ¿A qué hora llega su vuelo?', en: 'Yes, sure. What time is your flight?', kw: ['hora', 'vuelo'] },
        { who: 'you', es: 'Son las siete. ¿Cuánto tarda?', en: "Seven o'clock. How long does it take?", kw: ['siete', 'tarda'] },
        { who: 'them', es: 'Con tráfico, una hora. Son doscientos pesos.', en: 'With traffic, one hour. That is two hundred pesos.', kw: ['tráfico', 'doscientos'] },
        { who: 'you', es: 'Está bien. ¿Cuál es la mejor ruta?', en: "Okay. What's the best route?", kw: ['mejor', 'ruta'] },
        { who: 'them', es: 'La autopista. Salgo en dos minutos.', en: "The highway. I'm leaving in two minutes.", kw: ['autopista', 'salgo'] },
        { who: 'you', es: 'Gracias. El equipaje va al maletero.', en: 'Thanks. The luggage goes in the trunk.', kw: ['equipaje', 'maletero'] },
        { who: 'them', es: 'Como usted diga. ¡Buen viaje!', en: 'As you say. Have a good trip!', kw: ['usted', 'viaje'] },
      ],
    },
    {
      id: 'taqu', icon: '🌮', title: 'En la taquería', intro: "Lunchtime. You're hungry.",
      lines: [
        { who: 'you', es: 'Buenas tardes. Quiero un pastor con salsa, por favor.', en: 'Good afternoon. I want al pastor with salsa, please.', kw: ['pastor', 'salsa'] },
        { who: 'them', es: '¿Con tortilla de maíz o de harina?', en: 'With a corn tortilla or a flour one?', kw: ['maíz', 'harina'] },
        { who: 'you', es: 'De maíz, por favor. ¿Y qué hay de sopa?', en: 'Corn, please. And what soup do you have?', kw: ['maíz', 'sopa'] },
        { who: 'them', es: 'Sopa de tortilla y arroz con pollo.', en: 'Tortilla soup and chicken rice.', kw: ['tortilla', 'pollo'] },
        { who: 'you', es: 'Me llevo la sopa de tortilla, entonces.', en: "I'll take the tortilla soup then.", kw: ['llevo', 'sopa'] },
        { who: 'them', es: '¿Algo más? ¿Una bebida?', en: 'Anything else? A drink?', kw: ['algo', 'bebida'] },
        { who: 'you', es: 'Una agua de jamaica. ¿Cuánto es?', en: 'A hibiscus water. How much is it?', kw: ['jamaica', 'cuánto'] },
        { who: 'them', es: 'Doscientos cuarenta pesos. ¿Pagas aquí?', en: 'Two hundred forty pesos. Are you paying here?', kw: ['doscientos', 'pagas'] },
      ],
    },
  ];

  const A2D = [
    {
      id: 'medico', icon: '🩺', title: 'En el consultorio', intro: "You don't feel great. Appointment at 3 p.m.",
      lines: [
        { who: 'you', es: 'Doctor, tengo un dolor fuerte en el pecho desde anoche.', en: "Doctor, I've had a strong pain in my chest since last night.", kw: ['dolor', 'pecho'] },
        { who: 'them', es: '¿Desde cuándo lo siente? ¿Tiene fiebre?', en: 'Since when have you felt it? Do you have a fever?', kw: ['cuándo', 'fiebre'] },
        { who: 'you', es: 'Desde ayer. Treinta y ocho grados.', en: 'Since yesterday. Thirty-eight degrees.', kw: ['ayer', 'treinta'] },
        { who: 'them', es: 'Tome. Esto es para el dolor, cada ocho horas.', en: 'Take this. This is for the pain, every eight hours.', kw: ['dolor', 'ocho'] },
        { who: 'you', es: '¿Necesito receta o lo pago aquí?', en: 'Do I need a prescription or do I pay here?', kw: ['receta', 'pago'] },
        { who: 'them', es: 'Le doy la receta. El laboratorio abre hasta las nueve.', en: "I'll give you the prescription. The pharmacy is open until nine.", kw: ['receta', 'laboratorio'] },
        { who: 'you', es: '¿Cuánto cuesta la consulta?', en: 'How much is the consultation?', kw: ['cuánto', 'consulta'] },
        { who: 'them', es: 'Cien pesos. Vuelva si vuelve a dolerle.', en: 'A hundred pesos. Come back if it hurts again.', kw: ['cien', 'vuelva'] },
      ],
    },
  ];

  const B1D = [
    {
      id: 'trabajo', icon: '💼', title: 'Hablando con el jefe', intro: 'A quiet corner of the office. Friday is coming.',
      lines: [
        { who: 'you', es: 'Jorge, ¿tienes un momento? Quiero hablar del viernes.', en: 'Jorge, do you have a moment? I want to talk about Friday.', kw: ['momento', 'viernes'] },
        { who: 'them', es: 'Claro. ¿Qué pasa?', en: "Of course. What's up?", kw: ['claro', 'pasa'] },
        { who: 'you', es: 'Mi hija está enferma y necesito el viernes libre.', en: 'My daughter is sick and I need Friday off.', kw: ['hija', 'libre'] },
        { who: 'them', es: '¿La propuesta se puede mover? Es el día de la reunión.', en: "Can the proposal move? It's the meeting day.", kw: ['propuesta', 'reunión'] },
        { who: 'you', es: 'Puedo terminarla el jueves por la noche, yo.', en: 'I can finish it Thursday night, me.', kw: ['terminarla', 'jueves'] },
        { who: 'them', es: 'Está bien. Solo avisa a tu equipo antes del mediodía.', en: "Okay. Just let your team know before noon.", kw: ['avisa', 'mediodía'] },
        { who: 'you', es: 'Gracias, de verdad. Te debo una.', en: "Thanks, really. I owe you one.", kw: ['gracias', 'debo'] },
        { who: 'them', es: 'Aquí andamos. Avísame cómo está tu hija.', en: "We're here for each other. Let me know how your daughter is.", kw: ['avísame', 'hija'] },
      ],
    },
    {
      id: 'empleo', icon: '🏢', title: 'La entrevista de trabajo', intro: 'Monday, 10 a.m. The HR manager is already talking fast.',
      lines: [
        { who: 'you', es: 'Buenos días, señora López. Gracias por recibirme hoy.', en: 'Good morning, Mrs. López. Thank you for seeing me today.', kw: ['gracias', 'recibirme'] },
        { who: 'them', es: 'El gusto es mío. Hábleme de su experiencia.', en: 'The pleasure is mine. Tell me about your experience.', kw: ['gusto', 'experiencia'] },
        { who: 'you', es: 'Llevo seis años en logística. Lo último que hice fue coordinar un equipo de ocho personas.', en: 'I have been in logistics for six years. The last thing I did was coordinate a team of eight.', kw: ['logística', 'coordinar'] },
        { who: 'them', es: '¿Qué harías si el pedido llegara tarde otra vez?', en: 'What would you do if the order arrived late again?', kw: ['harías', 'tarde'] },
        { who: 'you', es: 'En primer lugar, avisaría al cliente. Después, buscaría otra ruta para entregar el mismo día.', en: 'First, I would warn the client. Then, I would find another route to deliver the same day.', kw: ['avisaría', 'ruta'] },
        { who: 'them', es: 'Su español me parece muy bueno. ¿De dónde es?', en: 'Your Spanish seems very good to me. Where are you from?', kw: ['español', 'dónde'] },
        { who: 'you', es: 'Soy de Monterrey, pero vivo aquí desde 2019. La verdad, me he sentido como en casa.', en: 'I am from Monterrey, but I have lived here since 2019. Honestly, I have felt like at home.', kw: ['Monterrey', 'casa'] },
        { who: 'them', es: 'Bien. El sueldo es negociable, pero el horario es de lunes a viernes, de nueve a seis.', en: 'Good. The salary is negotiable, but the schedule is Monday to Friday, nine to six.', kw: ['sueldo', 'horario'] },
        { who: 'you', es: 'Me parece perfecto. ¿Cuándo podría empezar?', en: 'That seems perfect to me. When could I start?', kw: ['perfecto', 'empezar'] },
        { who: 'them', es: 'El lunes que viene. Y traiga sus documentos el viernes, por favor.', en: 'Next Monday. And bring your documents on Friday, please.', kw: ['lunes', 'documentos'] },
      ],
    },
  ];

  return {
    levels: ['A1', 'A2', 'B1'],
    levelNames: { A1: 'A1 · Beginner', A2: 'A2 · Conversational', B1: 'B1 · Independent' },
    A1: { words: A1W, sentences: A1S, grammar: A1G, dialogues: A1D },
    A2: { words: A2W, sentences: A2S, grammar: A2G, dialogues: A2D },
    B1: { words: B1W, sentences: B1S, grammar: B1G, dialogues: B1D },
  };
})();
